export const homeObject = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightDesc: true,
    topLine: "Night Shy Photography for Begginers",
    headline: "Are you wondering how to start with astrophotography?",
    description: "If you would like to make absolute stunning night sky photos, just checkout the essentials you need!" +
        " ...you will be suprised! ",
    buttonLabel: "Get started!",
    imgStart: false,
    img: require("../../images/svg-1.svg").default,
    alt: "Sky",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjectTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightDesc: true,
    topLine: "Maybe you are looking for some tips?",
    headline: "What are the best conditions to make reeeally good photos?",
    description: "Remember to check out weather conditions, especially clouds, moon brightness and light pollution in the cities",
    buttonLabel: "Check here",
    imgStart: true,
    img: require("../../images/svg-2.svg").default,
    alt: "Moon",
    dark: false,
    primary: true,
    darkText: true,
};

export const homeObjectThree = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightDesc: false,
    topLine: "Night Shy Photography for Begginers",
    headline: "How to make your pictures looks even better?",
    description: "Don't be afraid of postproduction, stacking photos and using different applications to make your photos reflect as faithfully as possible what your eyes saw",
    buttonLabel: "Read more",
    imgStart: false,
    img: require("../../images/svg-3.svg").default,
    alt: "Postproduction",
    dark: true,
    primary: true,
    darkText: false,
};